// Copyright 2026 Sandwich Cake Studios. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/**
 * Native gameplay tags referenced from C++. They register themselves when the module loads,
 * so no manual initialization is needed.
 *
 * Designer-extensible roots (Steam.Achievement.*, Steam.Presence.*, ...) live in the plugin tag ini,
 * never here. A tag is defined in exactly one place.
 */
namespace SteamGameplayTags
{
	// Features
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_User);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Utility);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Overlay);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Stats);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Achievements);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Leaderboards);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Friends);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Presence);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Sessions);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Voice);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Input);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Cloud);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_DLC);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feature_Screenshots);

	// Errors
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Unavailable);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_NotInitialized);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_NotLoggedIn);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_FeatureDisabled);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_NotSupported);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_InvalidArgument);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Timeout);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Failed);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Cancelled);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_RateLimited);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Offline);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_QuotaExceeded);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_NotOwner);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_WrongScope);

	// Sessions and lobbies (Phase 9)
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Lobby_Full);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Lobby_NotFound);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Lobby_Denied);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Session_HostLeft);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Session_Timeout);
	SANDWICHSTEAM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Error_Session_Kicked);
}
