<#
.SYNOPSIS
  Keeps the documentation screenshots in sync with the pages that use them.

.DESCRIPTION
  1. Scans README.md and docs/**/*.md for   <!-- SHOT nn: description -->  followed by an image line.
  2. For every image that does not exist yet, creates an orange-bordered placeholder PNG with the shot ID
     and description drawn on it, so the site never shows a broken image.
  3. Rewrites docs/SHOT-LIST.md: a checklist where [x] means a real screenshot has replaced the placeholder.

  To add a screenshot: save your PNG over the placeholder with the SAME file name, then run this script again.
  Existing files are never overwritten.

  Run from the plugin folder:   powershell -ExecutionPolicy Bypass -File tools\Update-Screenshots.ps1
#>
Add-Type -AssemblyName System.Drawing

$root   = Split-Path -Parent $PSScriptRoot
$border = [System.Drawing.Color]::FromArgb(255, 255, 106, 0)   # placeholder marker colour, pixel (0,0)

function Test-IsPlaceholder([string]$Path) {
    $bmp = [System.Drawing.Bitmap]::FromFile($Path)
    try { return ($bmp.GetPixel(0, 0).ToArgb() -eq $border.ToArgb()) } finally { $bmp.Dispose() }
}

function New-Placeholder([string]$Path, [string]$Id, [string]$Text) {
    $bmp = New-Object System.Drawing.Bitmap 1280, 720
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = 'AntiAlias'
    $g.TextRenderingHint = 'AntiAlias'
    $g.Clear($border)
    $g.FillRectangle((New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(255, 43, 47, 58))), 8, 8, 1264, 704)
    $white = [System.Drawing.Brushes]::White
    $grey  = New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(255, 170, 176, 190))
    $g.DrawString("SCREENSHOT $Id", (New-Object System.Drawing.Font 'Segoe UI', 40, ([System.Drawing.FontStyle]::Bold)), $white, 60, 220)
    $rect = New-Object System.Drawing.RectangleF 60, 320, 1160, 300
    $g.DrawString($Text, (New-Object System.Drawing.Font 'Segoe UI', 24), $grey, $rect)
    $g.DrawString('Placeholder - replace this file with a real screenshot (same file name)', (New-Object System.Drawing.Font 'Segoe UI', 16), $grey, 60, 660)
    $g.Dispose()
    New-Item -ItemType Directory -Force -Path (Split-Path $Path) | Out-Null
    $bmp.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
}

$files = @(Get-Item (Join-Path $root 'README.md')) + @(Get-ChildItem (Join-Path $root 'docs') -Recurse -Filter *.md | Where-Object { $_.Name -ne 'SHOT-LIST.md' })
$shots = @()

foreach ($file in $files) {
    $lines = Get-Content $file.FullName -Encoding UTF8
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '<!--\s*SHOT\s+(\d+)\s*:\s*(.+?)\s*-->') {
            $id = $Matches[1]; $desc = $Matches[2]
            # the image is the next non-empty line
            $j = $i + 1
            while ($j -lt $lines.Count -and $lines[$j].Trim() -eq '') { $j++ }
            if ($j -lt $lines.Count -and $lines[$j] -match '!\[[^\]]*\]\(([^)]+\.png)\)') {
                $rel = $Matches[1]
                $abs = [System.IO.Path]::GetFullPath((Join-Path $file.DirectoryName $rel))
                $shots += [pscustomobject]@{ Id = $id; Desc = $desc; Page = $file.FullName.Substring($root.Length + 1).Replace('\', '/'); Rel = $rel; Abs = $abs }
            } else {
                Write-Warning "SHOT $id in $($file.Name) has no image line after it."
            }
        }
    }
}

$created = 0
foreach ($s in $shots) {
    if (-not (Test-Path $s.Abs)) { New-Placeholder $s.Abs $s.Id $s.Desc; $created++ }
}

$done = 0
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Screenshot shot list')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Generated by `tools/Update-Screenshots.ps1` - do not edit by hand.')
[void]$sb.AppendLine('`[x]` = real screenshot in place, `[ ]` = still a placeholder. Capture at 16:9 (1280x720 or larger), PNG, and save over the file with the **same name**.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Done | ID | File | Page | What to capture |')
[void]$sb.AppendLine('|---|---|---|---|---|')
foreach ($s in ($shots | Sort-Object { [int]$_.Id })) {
    $isReal = -not (Test-IsPlaceholder $s.Abs)
    if ($isReal) { $done++ }
    $mark = if ($isReal) { '[x]' } else { '[ ]' }
    $file = $s.Abs.Substring($root.Length + 1).Replace('\', '/')
    [void]$sb.AppendLine("| $mark | $($s.Id) | ``$file`` | $($s.Page) | $($s.Desc) |")
}
[System.IO.File]::WriteAllText((Join-Path $root 'docs\SHOT-LIST.md'), $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))

Write-Host "Shots: $($shots.Count) total, $done real, $($shots.Count - $done) placeholders ($created placeholder(s) created now)."
